import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 'punch-ananas-passion',
    name: 'Punch Ananas-Passion',
    slug: 'punch-ananas-passion',
    description: 'Un mariage tropical entre la douceur de l\'ananas et l\'intensite du fruit de la passion. Notes exotiques, finale vive et ensoleillée.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Ananas, Passion',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    ingredients: ['Ananas', 'Sirop de la passion', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-ananas-goyave',
    name: 'Punch Ananas-Goyave',
    slug: 'punch-ananas-goyave',
    description: 'L\'ananas rencontre la goyave dans un punch genereux aux aromes tropicaux. Doux, fruité, irresistible.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Ananas, Goyave',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    ingredients: ['Ananas', 'Goyave', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-passion',
    name: 'Punch Passion',
    slug: 'punch-passion',
    description: 'Toute l\'intensite du fruit de la passion dans un punch vif et parfume. Acidule, exotique, addictif.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Passion',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    ingredients: ['Fruit de la passion', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-coco',
    name: 'Punch Coco',
    slug: 'punch-coco',
    description: 'La douceur onctueuse du lait de coco mariee au rhum des iles. Cremeux, rond, un voyage sous les cocotiers.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Coco',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Lait de coco', 'Lait', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-pili-pili',
    name: 'Punch Pili-Pili',
    slug: 'punch-pili-pili',
    description: 'Un punch audacieux aux epices relevees et au sirop de grenade. Piquant, chaleureux, une explosion de caractere.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Pili-Pili',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Épices diverses', 'Sirop de grenade', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-coco-gingembre',
    name: 'Punch Coco-Gingembre',
    slug: 'punch-coco-gingembre',
    description: 'Le veloute du coco rehausse par la vivacite du gingembre frais. Epice, cremeux, un equilibre parfait.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Coco, Gingembre',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Lait de coco', 'Lait', 'Gingembre', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-goyave',
    name: 'Punch Goyave',
    slug: 'punch-goyave',
    description: 'La goyave des Caraibes dans toute sa splendeur. Sucre, parfume, un classique tropical revisité.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Goyave',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Goyave', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-mangue-ananas',
    name: 'Punch Mangue-Ananas',
    slug: 'punch-mangue-ananas',
    description: 'Deux fruits solaires reunis dans un punch gourmand et genereux. Sucre, tropical, une invitation au voyage.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Mangue, Ananas',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Mangue', 'Ananas', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
  {
    id: 'punch-mangue',
    name: 'Punch Mangue',
    slug: 'punch-mangue',
    description: 'La mangue mure a point, fondante et parfumee. Doux, veloute, le gout pur des tropiques.',
    price_cents: 2500,
    alcohol_degree: null,
    volume_ml: 700,
    flavor: 'Mangue',
    image_url: null,
    stock_quantity: 20,
    is_active: true,
    ingredients: ['Mangue', 'Sirop de cannes', 'Rhum', 'Arômes'],
    volume: '70cl',
    created_at: new Date().toISOString(),
  },
];

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.is_featured).slice(0, 3);
}

export function getAllProducts(): Product[] {
  return PRODUCTS.filter(p => p.is_active);
}

export function getProductBySlug(slug: string): Product | null {
  return PRODUCTS.find(p => p.slug === slug) || null;
}
